### ISSUE TITLE
Run Backend mapnik errors with no styles to load - seems lots of ENV vars and none of them setup or described

### ISSUE THREAD

**Issue by bib1963** [openstreetmap/tirex#26]
In lib/Tirex/Backend.pm, there are a number of vars being setup/required:
    my $renderer_name   = $ENV{'TIREX_BACKEND_NAME'}            or $self->error_disable('missing TIREX_BACKEND_NAME');
    my $port            = $ENV{'TIREX_BACKEND_PORT'}            or $self->error_disable('missing TIREX_BACKEND_PORT');
    my $syslog_facility = $ENV{'TIREX_BACKEND_SYSLOG_FACILITY'} or $self->error_disable('missing TIREX_BACKEND_SYSLOG_FACILITY');
    my $mapfiles        = $ENV{'TIREX_BACKEND_MAP_CONFIGS'}     or $self->error_disable('missing TIREX_BACKEND_MAP_CONFIGS');
    my $alive_timeout   = $ENV{'TIREX_BACKEND_ALIVE_TIMEOUT'}   or $self->error_disable('missing TIREX_BACKEND_ALIVE_TIMEOUT');
    my $pipe_fileno     = $ENV{'TIREX_BACKEND_PIPE_FILENO'}     or $self->error_disable('missing TIREX_BACKEND_PIPE_FILENO');
    my $socket_fileno   = $ENV{'TIREX_BACKEND_SOCKET_FILENO'};

    $Tirex::DEBUG = 1 if (defined $ENV{'TIREX_BACKEND_DEBUG'});

Seems when I run the backend mapnik directly, to find what the heck is keeping it from running, it errors out with:
Cannot load any Mapnik styles

Looking at the source, it seems TIREX_BACKEND_MAP_CONFIGS at least, has to be setup. Yet no where is this described.

I am going to hazard a guess here and say, to get tirex up and running, there is a lot which has to be setup, and is not described anywhere. It would be nice to see devs install clean, from the install docs and see how far they get. Anything additional they have to do, must be documented.

Ah well, back to the broken, but at least it runs for a while, renderd.

**Comment by woodpeck** [comment]
The enviroment variables are an internal implementation detail, set by the "backend manager" and consumed by individual backends. The individual backends are not meant to be run on their own. Instread, run the tirex-backend-manager with the "-f" command line option to keep it from detaching, this will give you debug output of the backends on stdout.

**Comment by bib1963** [comment]
On Thursday, 29 April 2021 11:56:14 BST Frederik Ramm wrote:
> The enviroment variables are an internal implementation detail, set by the "backend manager" and consumed by individual backends. The individual backends are not meant to be run on their own. Instread, run the tirex-backend-manager with the "-f" command line option to keep it from detaching, this will give you debug output of the backends on stdout.
> 
> 

The ONLY files TIREX_BACKEND_MAP_CONFIGS is referenced in are:
/home/src/build/tirex/lib/Tirex/Backend.pm
/home/src/build/tirex/test/backend-test.sh
/home/src/build/tirex/backend-mapnik/renderd.cc
/home/src/build/tirex/backend-mapnik/test/test.sh

And the grep results:
/home/src/build/tirex/lib/Tirex/Backend.pm:    my $mapfiles        = $ENV{'TIREX_BACKEND_MAP_CONFIGS'}     or $self->error_disable('missing TIREX_BACKEND_MAP_CONFIGS');
/home/src/build/tirex/test/backend-test.sh:export TIREX_BACKEND_MAP_CONFIGS="etc/renderer/test/checkerboard.conf.dist"
/home/src/build/tirex/bin/tirex-backend-manager:    $ENV{'TIREX_BACKEND_MAP_CONFIGS'}     = join(' ', map { $_->get_filename() } $renderer->get_maps());
/home/src/build/tirex/backend-mapnik/renderd.cc:    tmp = getenv("TIREX_BACKEND_MAP_CONFIGS");
/home/src/build/tirex/backend-mapnik/test/test.sh:export TIREX_BACKEND_MAP_CONFIGS=test.conf

So, 2 of them are test files which set them up, 2 reference them, and one sets it up. NOWHERE is are these things described. You are not making things easy for people to get involved, since their first step is to get it up and running.

And the results of /opt/tirex/usr/bin/tirex-backend-manager -f --config /opt/tirex/etc/tirex/
Cannot load any Mapnik styles
Cannot load any Mapnik styles
Cannot load any Mapnik styles
Cannot load any Mapnik styles
Cannot load any Mapnik styles
Cannot load any Mapnik styles
