### ISSUE TITLE
Debian and Ubuntu packages

### ISSUE THREAD

**Issue by pantierra** [openstreetmap/tirex#36]
Hi, thanks for creating and maintaining `tirex`!

After `libapache2-mod-tile` and `renderd` are now officially included in the latest releases of Debian and Ubuntu and `libapache2-mod-tile` [is prepared and explicitly reocmmends](https://packages.debian.org/bullseye/libapache2-mod-tile) to work with `tirex` as well, it would be great to bring `tirex` into the official repositories, too.

We could do this with the super valuable support of the [Debian GIS Team](https://debian-gis-team.pages.debian.net/) - as I did with `mod_tile` - mainly working on the packaging in a repository on [salsa.debian.org/debian-gis-team/tirex](https://salsa.debian.org/debian-gis-team/tirex/), with review and all communication over [this mailing list](https://alioth-lists.debian.net/cgi-bin/mailman/listinfo/pkg-grass-devel).

It would be nice to collaborate with you on that. We could make it to the next Ubuntu LTS release, beginning of next year.

**Comment by woodpeck** [comment]
What would we have to do for that?

**Comment by pantierra** [comment]
You don't have to do a lot, but you can, of course. Anything from being responsive on some questions to taking actively part in the packaging on salsa.debian.org (everyone can create an account and we can request you access) would be super helpful.

This is my very rough bullet point list of things to do:

* [x] strip off logrotate link (either patch or upstream #34)
* [x] add `systemd` services 
* [x] Fix or exclude initd-scripts (the question is whether to offer also init-scripts in the packages. It doesn't have to, but it would be nice to do. However I would not like to invest into testing, as I don't use them. How do you think about them?)
* [x] Use mostly a single `tirex` package (and decide which backends and plugins to include and which not; can you give me your thoughts on that? Do you consider the additional backends for `wms`, `tms`, and `mapserver` sufficiently stable to include them? What about the plugins? `tirex-syncd` I would include for sure, or have it as a second package maybe.)
* [x] make it build, work, run through lintian (Debians QA tool)
* [x] test the package: review (several cycles with maintainers, power users and the Debian-GIS-Team), fix  and improve things.
* [x] submit as package to Debian (this takes a few months until it goes through all the reviews and tests), but once it has been accepted and builds well, it is quite quickly into `testing` and included in upcoming Ubuntu releases as well).

If I make it to the hackweekend, maybe we can also connect and advance on a few things.

**Comment by stoecker** [comment]
Note that tirex is packaged for openSUSE for years now including systemd services:

https://build.opensuse.org/package/show/Application:Geo/tirex

When looking a the other requests with the path changes: Generally following the FHS is fine, but better would be to follow FHS AND make it configurable on build time :-)

**Comment by xamanu** [comment]
Pretty cool, that tirex is in openSUSE and thanks for the link to the files!

**Comment by pantierra** [comment]
Thanks for the input @stoecker! Very nice, that `tirex` is packaged for openSUSE!

I advanced a bit and now have a well building package for Debian (in [its repo](https://salsa.debian.org/debian-gis-team/tirex)), using systemd services for the daemons, and I was able to reduce all serious lintian errors and warnings. Currently, I'm struggling a bit with the configuration, but it just will need a bit more time, and there are a few details that need some attention.

**Comment by pantierra** [comment]
Just pushed test builds of `tirex` to [deb.openbuildingmap.org](https://deb.openbuildingmap.org/). I'd appreciate people to test and find as many errors as possible (!), use any complex setup you are running. Now we can fix things easily. Let me know if you find any problem, either here or reach me on IRC as `xamanu`. Thank you!

**Comment by pantierra** [comment]
tirex [is now in Debian's NEW queue](https://ftp-master.debian.org/new/tirex_0.7.0-1~exp1.html), where it will undergo a final manual review, which usually takes a few months. All future releases will then be a matter of days to get it into testing.

**Comment by stephankn** [comment]
something looks broken with debian build:

checkout latest master 5a7bfe65390f720e8cd16fe1edfd7dc03b6cc2a7

```
# make -j12 deb
debuild -I -us -uc
[...]
dh_install: warning: Cannot find (any matches for) "/usr/libexec/tirex-syncd" (tried in /home/Tirex/debian/tmp, debian/tmp)

dh_install: warning: tirex-syncd missing files: /usr/libexec/tirex-syncd
dh_install: error: missing files, aborting
make: *** [debian/rules:48: binary-arch] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -I failed
make: *** [Makefile:83: deb] Error 29
```

**Comment by pantierra** [comment]
Thanks, @stephankn! This issue however is not about the Debian package instructions inside this code base. But rather about making this software available as official  packages in Debian and Ubuntu.  For tihs, I actually strip out the `debian` directory of this repo and replace it with the one the Debian GIS Team maintains in a [separate repository](https://salsa.debian.org/debian-gis-team/tirex).

**Comment by stephankn** [comment]
I see. Unfortunately, changes done in this context prevented `make deb` from working. So a local build was no longer possible.

**Comment by pantierra** [comment]
Oh, not nice. All the more thanks for fixing this problem!

**Comment by pantierra** [comment]
`tirex` has been [included in Ubuntu](https://packages.ubuntu.com/kinetic/tirex) since version 22.10 and it is going to be part of the upcoming Debian 12 release. Closing here.
